apiVersion: v1
kind: Pod
metadata:
  name: demo
  labels:
    aadpodidbinding: "Team3PodID"
spec:
  containers:
  - name: demo
    image: mcr.microsoft.com/oss/azure/aad-pod-identity/demo:v1.6.3
    args:
      - --subscriptionid=5239decf-2a5b-497d-9f85-b64f45c13a65
      - --clientid=b49e5c61-c930-4a07-a4e2-5876b8eb349e
      - --resourcegroup=MC_teamResources_Team3AKS2_northeurope
    env:
      - name: MY_POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: MY_POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: MY_POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
  nodeSelector:
    kubernetes.io/os: linux